config/routes.rb
Rails.application.routes.draw do
  resources :lobbies

  get 'welcome/index'
  root 'lobbies#index'
  get 'welcome/about'
  get 'teams/:id' , to: 'teams#update'

  post 'auth/steam/callback' => 'auth#auth_callback'
  get 'logout' => 'auth#logout'

end

app/models/lobby.rb
class Lobby < ActiveRecord::Base
	has_many :teams, dependent: :destroy
	after_create :init

	def init
		@lobby = Lobby.last
		@lobby.numPlayer = 0
		for i in 1..5
	      @lobby.teams.create(pos: i,side: true,free: true)
	    end
    	for i in 1..5
	      @lobby.teams.create(pos: i,side: false,free: true)
	    end
		@lobby.save
	end
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
	belongs_to :lobby
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  # auth callback POST comes from Steam so we can't attach CSRF token
  skip_before_filter :verify_authenticity_token, :only => :auth_callback

  def auth_callback
    auth = request.env['omniauth.auth']
    session[:user] = { :nickname => auth.info['nickname'],
                       :image => auth.info['image'],
                       :uid => auth.uid }
    redirect_to root_url
  end

  def logout
    session.delete(:user)
    redirect_to root_url
  end
end

app/controllers/lobbies_controller.rb
class LobbiesController < ApplicationController
  before_action :set_lobby, only: [:show, :edit, :update, :destroy]

  # GET /lobbies
  # GET /lobbies.json
  def index
    @lobbies = Lobby.all
    @lobbies.each do |lobby|
      if(lobby.numPlayer == 0)
        lobby.destroy
      end
    end
  end

  # GET /lobbies/1
  # GET /lobbies/1.json
  def show
    @lobby = Lobby.find(params[:id])
    #@teams = Team.find_by(lobby_id: @lobby.id)
    @teams = @lobby.teams
    session[:user]['position'] = 'lobby'
    @lobby.numPlayer+=1
    @lobby.save
  end


  # GET /lobbies/new
  def new
    @lobby = Lobby.new
  end

  # GET /lobbies/1/edit
  def edit
  end

  # POST /lobbies
  # POST /lobbies.json
  def create
    @lobby = Lobby.new(lobby_params)

    respond_to do |format|
      if @lobby.save
        format.html { redirect_to @lobby, notice: 'Lobby was successfully created.' }
        format.json { render :show, status: :created, location: @lobby }
      else
        format.html { render :new }
        format.json { render json: @lobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lobbies/1
  # PATCH/PUT /lobbies/1.json
  def update
    respond_to do |format|
      if @lobby.update(lobby_params)
        format.html { redirect_to @lobby, notice: 'Lobby was successfully updated.' }
        format.json { render :show, status: :ok, location: @lobby }
      else
        format.html { render :edit }
        format.json { render json: @lobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lobbies/1
  # DELETE /lobbies/1.json
  def destroy
    @lobby.destroy
    respond_to do |format|
      format.html { redirect_to lobbies_url, notice: 'Lobby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lobby
      @lobby = Lobby.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lobby_params
      params.require(:lobby).permit(:name, :loc, :numPlayer, :skill)
    end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
	def update
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/lobbies_helper.rb
module LobbiesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dota Match</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Dota<i>Match</i></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li class="<%= 'active' if current_page?(root_path) %>"><a href="/">Public Matches</a></li>
      <li class="<%= 'active' if current_page?(welcome_about_path) %>"><a href="welcome/about">About</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if session.key? :user %>
        <% user = session[:user] %>
        <li><a href="/mymatches">Hi <%= user['nickname'] %></a></li>
        <li><%= image_tag user['image'], class: 'avatar' %></li>
        <li><a href="/logout">Logout</a></li>
      <% else %>
        <li><%= link_to image_tag("http://cdn.steamcommunity.com/public/images/signinthroughsteam/sits_small.png"), '/auth/steam' %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
<%= yield %>

</body>
</html>

app/views/lobbies/_form.html.erb
<%= form_for(@lobby) do |f| %>
  <% if @lobby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lobby.errors.count, "error") %> prohibited this lobby from being saved:</h2>

      <ul>
      <% @lobby.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :loc %><br>
    <%= f.text_field :loc %>
  </div>
  <div class="field">
    <%= f.label :skill %><br>
    <%= f.number_field :skill %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lobbies/edit.html.erb
<h1>Editing lobby</h1>

<%= render 'form' %>

<%= link_to 'Show', @lobby %> |
<%= link_to 'Back', lobbies_path %>

app/views/lobbies/index.html.erb
<div class="container center">
<h1>Create or join a lobby</h1>

<% if session.key? :user %>
<a href="lobbies/new"><button type="button" class="btn btn-success">New Lobby</button></a>
<% end %>

<div class="tavola" id="table">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Loc</th>
      <th>Numplayer</th>
      <th>Skill Level</th>
      <th>Positions Available</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lobbies.each do |lobby| %>
      <tr>
        <td><%= lobby.name %></td>
        <td><%= lobby.loc %></td>
        <td><%= lobby.numPlayer %>/10</td>
        <td><%= lobby.skill %></td>
        <td>
          <% lobby.teams.each do |team| %>
            <span style= <% if team.free == true %>"color:green" <% else %> "color:red" <% end %>><%=team.pos%></span>
            <% end %>
        </td>
        <% if session.key? :user %>
        <td><%= link_to 'Enter Lobby', lobby %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
</div>

app/views/lobbies/new.html.erb
<h1>New lobby</h1>

<%= render 'form' %>

<%= link_to 'Back', lobbies_path %>

app/views/lobbies/show.html.erb
<div class="container md-5">
<p id="notice"><%= notice %></p>

<h2>
  <strong>Name:</strong>
  <%= @lobby.name %>

  <strong>Loc:</strong>
  <%= @lobby.loc %>
  <strong>Numplayer:</strong>
  <%= @lobby.numPlayer %>
  <strong>Skill:</strong>
  <%= @lobby.skill %>
</h2>

</div>

<div class="container col-md-6">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>rank</th>
      </tr>
    </thead>

    <tbody>
      <% @teams.each_with_index do |team, pos| %>
      <% if team.side == true%>
        <tr>
          <td><%= pos +1%></td>
          <td><% if team.free == true %> free <% else %> <%= team.player %><% end %></td>
          <td></td>
        </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<div class="container col-md-6">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>rank</th>
      </tr>
    </thead>

    <tbody>
      <% @teams.each_with_index do |team, pos| %>
      <% if team.side == false%>
        <tr>
          <td><%= team.pos %></td>
          <td><% if team.free == true %> free <% else %> <%= team.player %><% end %></td>
          <td></td>
        </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/welcome/about.html.erb
<h1>about</h1>

app/views/welcome/index.html.erb
<div class="container">
	<h2>Join a lobby to begin.</h2>
</div>